spring.application.name=erp-telecom
server.port = 8001
spring.datasource.url = jdbc:mysql://localhost:3306/erp-telecom
spring.datasource.username = root
spring.datasource.password = admin
spring.jpa.hibernate.ddl-auto =update

# Exclusion endpoints (Added 23/09/25)
security.jwt.exclude-endpoints = /users/register,users/login

## Root logging level (Added 23/09/25)
#logging.level.root=INFO
#
## Your package at DEBUG (logs only for erp_telecom) (Added 23/09/25)
#logging.level.com.atharva.erp_telecom=DEBUG
#
## Log file output (Added 23/09/25)
#logging.file.name=logs/erp-telecom.log
#
## Log pattern (console) (Added 23/09/25)
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
#
## Log pattern (file) (Added 23/09/25)
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

